package com.pct.device.payload;

import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Data
@Setter
@Getter
@NoArgsConstructor
public class DeviceReportPayload {

	private String DeviceID;
	private String Customer;
	private String VIN;
	private String AssetID;
	private String Event;
	private int EventId;
	private String ReceivedTime;
	private int Seq;
	private String RTCTime;
	private String GPSTime;
	private String GPS;
	private Double Lat;
	private Double Long;
	private String LatLong;
	private String MainV;
	private String AltV;
	private String BatrV;
	private String ChargingV;
	
	private String DeviceStatus;
	private String Power;
	private String InTrip;
	private String Ignition;
	private String InMotion;
	private String Tamper;
	
	private String Altitude;
	private Float MPH;
	private Float kPH;
	private int Heading;
	private double Odometer;
	private int Fuel;
	private String ODTMILMiles;
	private String ODTDTCClearMiles;
	private Float AccInfo;
	private Float AccX;
	private Float AccY;
	private Float AccZ;
	private Float AccCalibX;
	private Float AccCalibY;
	private Float AccCalibZ;
	private String Orientation;
	private Float OrientX;
	private Float OrientY;
	private Float OrientZ;
	private Float IntTemp;
	private Float AmbientTemp;
	private int RSSI;
	private String HDOP;
	private String Sats;
	private String Service;
	private String Roaming;
	private String Country;
	private String Network;
	private String TowerID;
	private String CentroidLat;
	private String CentroidLong;
	private String Band;
	private String RxTxEc;
	private String APPVer;
	private String OSVer;
	private String HWVer;
	private String HWRev;
	private String IOVer;
	private String ExtenderVer;
	private String BLEVer;
	private String ConfigChg;
	private String Config;
	private String ConfigDesc;
	private String Devdefcfg;
	private String DevdefcfgCRC;
	private String Devdef2cfg;
	private String Devdef2cfgCRC;
	private String Devdef3cfg;
	private String Devdef3cfgCRC;
	private String Devdef4cfg;
	private String Devdef4cfgCRC;
	private String Devusrcfg;
	private String DevusrcfgCRC;
	private String GPIO;
	private String TFTPStatus;
	private String PeripheralVersion;
	private String ABS;
	private String ABSOdometer;
	private String ABSInfo;
	private String AirSupply;
	private String ATIS;
	private String WheelEnd;
	private String SFKWheelEnd;
	private String AlphaTpms;
	private String Receiver;
	private String LOF1;
	private String LOF1Temp;
	private String LOF1Psi;
	private String LIF2;
	private String LIF2Temp;
	private String LIF2Psi;
	private String RIF3;
	private String RIF3Temp;
	private String RIF3Psi;
	private String ROF4;
	private String ROF4Temp;
	private String ROF4Psi;
	private String LOR5;
	private String LOR5Temp;
	private String LOR5Psi;
	private String LIR6;
	private String LIR6Temp;
	private String LIR6Psi;
	private String RIR7;
	private String RIR7Temp;
	private String RIR7Psi;
	private String ROR8;
	private String ROR8Temp;
	private String ROR8Psi;
	
	
	
	private String BetaTPMS;
	private String Receivers;
	
	private String LOF;
	private String LOF1TempBeta;
	private String LOF1PsiBeta;
	private String LIF;
	private String LIF1Temp;
	private String LIF1Psi;
	private String RIF;
	private String RIF1Temp;
	private String RIF1Psi;
	private String ROF;
	private String ROF1Temp;
	private String ROF1Psi;
	private String LOR;
	private String LOR1Temp;
	private String LOR1Psi;
	private String LIR;
	private String LIR1Temp;
	private String LIR1Psi;
	private String RIR;
	private String RIR1Temp;
	private String RIR1Psi;
	private String ROR;
	private String ROR1Temp;
	private String ROR1Psi;

	private String BeaconSmartPair;

	private String BrakeStroke;
	private String ChassisCargo;
	private String Thumbnail;
	private String PredictionValue;
	private String State;
	private String Loaded;
	private String ConfidenceRating;
	private String Door;
	private String DoorWireless;
	
	private String LiftgateVoltage;
	private String StateOfCharge;
	private String LiftGateCycles;
	private String Motor1Runtime;
	private String Motor2Runtime;
	private String StatusFlags;

	private String LightOut;
	private String Reefer;

	private String Status;
	private String TempControl;
	private String AirFlow;
	private String TankSaverBeta;
	private String TempMinew;
	
	private String CommStatus;
	private String SensorId;
	private String AgeOfReading;
	private String SensorStatus;
	private String Humidity;
	private String Temperature;
	private String BatteryLevel;

	private String BleSensorStatus;
	private String BleTemperatureReadings;
	private String TempWirelessStatus;
	private String TempWirelessReadings;

	private String ACKn;
	private String DeviceIP;
	private String RawReport;

//	private String deviceId;
//	private String companyId;
//	private String vin;
//	private String io;
//	private int eventId;
//	private String receivedTimeStamp;
//	private int sequence;
//	private String rtcDateTimeInfoStr;
//	private String gpsTime;
//	private int gpsStatusIndex;
//	private float latitude;
//	private float longitude;
//	private String latLong;
//	private float mainPower;
//	private float auxPower;
//	private float batteryPower;
//	private float chargePower;
//
//	private String deviceStatus;
//	private long altitudeFeet;
//	private float speedMiles;
//	private int speedKms;
//	private int heading;
//	private double odometerKms;
//	private String fuelLevelPercentage;
//	private String odtsince_milmiles;
//	private String odtsince_dtcclear_miles;
//	private String accelerometer_xmm_s2;
//	private String accelerometer_xmm_s2_x;
//	private String accelerometer_xmm_s2_y;
//	private String accelerometer_xmm_s2_z;
//	private String accelerometer_fields_x;
//	private String accelerometer_fields_y;
//	private String accelerometer_fields_z;
//	private String orientation_status;
//	private String rientation_xaxis_milli_gs_x;
//	private String rientation_xaxis_milli_gs_y;
//	private String rientation_xaxis_milli_gs_z;
//	private String internal_temperature;
//	private String ambient_temperature;
//
//	private String rssi;
//	private String hdop;
//	private String num_satellites;
//	private String service_type_index;
//	private String roaming_index;
//	private String mobile_country_code;
//	private String mobile_network_code;
//	private String tower_id;
//	private String tower_centroid_latitude;
//	private String tower_centroid_longitude;
//	private String cellular_band;
//	private String rx_tx_ec;
//	private String app_version;
//	private String os_version;
//	private String hw_id_version;
//	private String hw_version_revision;
//	private String hw_version_revision_io;
//	private String extender_version;
//	private String ble_version;
//	private String device_config_changed;
//	private String device_config;
//	private String configuration_desc;
//	private String config1_id;
//	private String config1_crc;
//	private String config2_id;
//	private String config2_crc;
//	private String config3_id;
//	private String config3_crc;
//	private String config4_id;
//	private String config4_crc;
//	private String config5_id;
//	private String config5_crc;
//	private String gpio_status;
//	private String tftp_status;
//	private String peripheral_version;
//	private String abs_status;
//	private String odometer;
//	private String beta_abs_id_status;
//	private String psi_air_supply_measure;
//	private String condition;
//	private String psi_wheel_end_measure;
//	private String SFK Wheel End_comm_status;
//	private String tpms_measures;
//	private String tpms_beta_measure;
//	private String comm_status;
//	private String undefined;
//	private String undefined;
//	private String uri;
//	private String status;
//	private String comm_status;
//	private String undefined;
//	private String status;
//	private String comm_status;
//	private String status;
//	private String ack_n;
//	private String device_ip;
//	private String rawreport;

}
