version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/pct-services/pct-administration

permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: ./cicd/stop_server.sh
      runas: root
  AfterInstall:
    - location: ./cicd/copy_frontend.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./cicd/start_server.sh
      timeout: 300
      runas: root
